### ISSUE TITLE
Fail to install netlify cli action

### ISSUE THREAD

**Issue by Wyfy0107** [netlify/actions#54] opened 2022-01-10 10:30 UTC
We're using this action in ubuntu-latest environment, with node 12.x 
The installation failed with some weird logs below

![Screenshot 2022-01-10 at 12 27 39](https://user-images.githubusercontent.com/63753802/148751273-084139c6-403b-486a-80c8-5079acbb561f.png)

**Comment by bogdibota** [comment] 2022-01-10 10:50
got the same error

it's caused by this https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by henrikq** [comment] 2022-01-10 12:40
maybe related to https://github.com/netlify/cli/issues/3788 ?

**Comment by sawa-zen** [comment] 2022-01-11 06:23
npm seems to have removed the problematic version of colors.js, so I think it's working now!

**Comment by AdrienFromToulouse** [comment] 2022-01-11 09:27
👋 I think it does not completely solve the issue. The build is ok BUT the deploy now fails silently with `RangeError: Invalid array length`.

Do you confirm the same issue?

*update* ok sorry, this fix is not yet on master.

**Comment by sawa-zen** [comment] 2022-01-11 10:12
Oops. I was experiencing the same problem 😵‍💫  I'm sorry I didn't notice.
<img width="1054" alt="log" src="https://user-images.githubusercontent.com/3971271/148923532-f0bf9917-0112-4dd5-bfc5-694628ba6f96.png">

**Comment by AdrienFromToulouse** [comment] 2022-01-11 10:17
Although it seems that moving to npm will introduce another issue of access right during the build:

https://github.com/netlify/cli/issues/1870

do you reproduce on your CI too?

**Comment by AdrienFromToulouse** [comment] 2022-01-11 10:18
For instance I tried that branch which implements the fix `uses: mannum/netlify-actions/cli@master` and face the issue

https://github.com/mannum/netlify-actions/blob/master/cli/Dockerfile#L12

I am running on `runs-on: ubuntu-latest`

**Comment by AdrienFromToulouse** [comment] 2022-01-11 10:21
> Oops. I was experiencing the same problem 😵‍💫 I'm sorry I didn't notice. <img alt="log" width="1054" src="https://user-images.githubusercontent.com/3971271/148923532-f0bf9917-0112-4dd5-bfc5-694628ba6f96.png">

I think you are still using yarn, but the package has been somehow "removed" to not create anymore issues. This seems to be a side effect.

**Comment by sawa-zen** [comment] 2022-01-11 10:22
OK. I'll try mannum/netlify-actions too.

**Comment by AdrienFromToulouse** [comment] 2022-01-11 10:23
It would be nice if the Netlify team could maintain this and put that into their OKRs, especially for paid customer.
#rant

**Comment by AdrienFromToulouse** [comment] 2022-01-11 10:29
I found it, that requires to upgrade the node version of the image to the most recent if we want to use npm:
https://github.com/netlify/cli/issues/1870#issuecomment-799845077

Their version is still node 12 on master.

**Comment by Wyfy0107** [comment] 2022-01-11 10:48
@AdrienFromToulouse Just to be sure, the current fix would be to use ` mannum/netlify-actions` with node latest ?

**Comment by AdrienFromToulouse** [comment] 2022-01-11 11:01
I don't know why with Yarn it keeps failing but using npm you need a recent version of node/npm. Works on my end with

```dockerfile
FROM node:16-alpine

LABEL version="1.0.1"
LABEL repository="http://github.com/netlify/actions"
LABEL homepage="http://github.com/netlify/actions/netlify"
LABEL maintainer="Netlify"
LABEL "com.github.actions.name"="Netlify"
LABEL "com.github.actions.description"="Wraps the Netlify CLI to enable common Netlify commands"
LABEL "com.github.actions.icon"="cloud"
LABEL "com.github.actions.color"="blue"

RUN npm install -g netlify-cli

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

@Wyfy0107 you may just fork netlify action and modify the dockerfile and point to your own fork.

**Comment by sawa-zen** [comment] 2022-01-11 11:52
Huh? I can now deploy with `netlify/actions/cli@master`.
<img width="895" alt="log" src="https://user-images.githubusercontent.com/3971271/148937885-48b1308d-8d54-4b02-a0d5-a375764270cc.png">

**Comment by AdrienFromToulouse** [comment] 2022-01-11 11:54
May be some cache on yarn? idk

**Comment by sawa-zen** [comment] 2022-01-11 12:01
I don't know either ¯\_(ツ)_/¯

@AdrienFromToulouse 
If you try `netlify/actions/cli@master` now, will it succeed?

**Comment by Wyfy0107** [comment] 2022-01-12 09:37
I tried again yesterday and it works now 😅

**Closed as completed** 2022-09-18 16:07 UTC
