### ISSUE TITLE
Github action error on publish: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by TravisKool** [netlify/actions#27] opened 2020-04-09 03:20 UTC
This was working fine on 4/7/2020 around 8PM. I just tried to publish again tonight and ran into this GitHub Action publish error 
### **"TypeError: Cannot read property 'replace' of null"**

**Here is the publish command i was using**
- name: Publish generated Blazor webassembly to Netlify
      uses: netlify/actions/cli@master
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=dist/wwwroot --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

Here is the full error:
TypeError: Cannot read property 'replace' of null
    at resolvePath (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/files.js:36:22)
    at searchBaseConfigFile (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/path.js:44:20)
    at getConfigPath (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/path.js:20:7)
    at getFullConfig (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/main.js:140:28)
    at loadConfig (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/main.js:112:13)
    at resolveConfig (/usr/local/share/.config/yarn/global/node_modules/@netlify/config/src/main.js:59:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.getConfig (/usr/local/share/.config/yarn/global/node_modules/netlify-cli/src/utils/command.js:76:14)
    at async DeployCommand.init (/usr/local/share/.config/yarn/global/node_modules/netlify-cli/src/utils/command.js:37:26)
    at async DeployCommand._run (/usr/local/share/.config/yarn/global/node_modules/@oclif/command/lib/command.js:43:13)
  Complete job

**Comment by haphut** [comment] 2020-04-09 07:33
The publishing action also seems to return success after this error.

**Comment by zoltanbedi** [comment] 2020-04-09 07:33
This is a duplicate of https://github.com/netlify/cli/issues/809 . The error is in netlify-cli not in the action.

**Comment by zipme** [comment] 2020-04-09 08:37
Until a new version of netlify/cli is released, you can use this fork `zipme/actions/cli@master` instead

**Comment by haphut** [comment] 2020-04-09 14:39
The issue has been fixed for me due to https://github.com/netlify/cli/issues/809#issuecomment-611541753.

Solving #19 with https://github.com/netlify/actions/issues/19#issuecomment-565837554 could have prevented this issue as one could pin a certain image in GitHub Actions.

**Comment by TravisKool** [comment] 2020-04-09 16:29
Wow thank you for fixing this!

This is now fixed as of this morning

![image](https://user-images.githubusercontent.com/5742961/78918000-8ec71d00-7a44-11ea-8439-a29a353e44e3.png)

**Closed as completed** 2020-04-13 11:06 UTC
